import React from "react";
// Assuming tileData is a large object imported correctly
import tileData, {WORMHOLE_SYMBOLS, EXPANSIONS} from "../data/tileData";
import boardData from "../data/boardData.json";
import raceData from "../data/raceData.json";

class MapInfo extends React.Component{
    constructor(prop){
        super(prop);
        this.state = {
            // Renamed to 'legendaries' for consistency with usage
            legendaries: [],
            resources: -1,
            influence: -1,
            spaceStations: -1
        };
        // Bind the single, unified processing function
        this.processMapTiles = this.processMapTiles.bind(this);
    };
    
    componentDidMount() {
        if (this.props.tiles && this.props.tiles.length > 0) {
            console.log("MapInfo: Processing initial map.");
            this.processMapTiles(this.props.tiles);
        } else {
            console.log("MapInfo: No tiles passed on initial load. State remains empty.");
        }
    }   

    /**
     * Executes every time new props or state are received.
     * CRITICAL: Used to detect when a new map is generated by the parent.
     */
    componentDidUpdate(prevProps) {
        // 🛑 CRITICAL CHECK: Only run if the 'tiles' array reference has changed.
        if (this.props.tiles !== prevProps.tiles) {
            console.log("MapInfo: Detecting new map generation. Processing new tiles in single pass.");
            
            if (this.props.tiles && this.props.tiles.length > 0) {
                // Call the single unified function; it will handle calculating and setting all state.
                this.processMapTiles(this.props.tiles);
            }
        }
    }

    /**
     * Consolidates all map calculations (Legendaries, Resources, Influence, Space Stations)
     * into a single pass over the 'tiles' array for optimal O(N) performance.
     */
    processMapTiles(tiles) {
        let newLegendaryPlanets = [];
        let newResources = 0;
        let newInfluence = 0;
        let newSpaceStations = 0;

        // Iterate through all the map tiles ONCE
        for (const tile of tiles) {
            const currentTileData = tileData.all[tile];

            // CRITICAL CHECK: Does the tile exist and does it contain planets?
            if (currentTileData && currentTileData.planets.length > 0) {
                
                // Continue allows us to skip tiles (like green/empty space) that don't need planet processing.
                if (currentTileData.type === "green") {
                    continue;
                }

                const planets = currentTileData.planets;
                
                // Iterate through all planets in the current tile
                for (const planet of planets) {
                    
                    // 1. Legendary Check
                    if (planet.legendary === true) {
                        newLegendaryPlanets.push(planet);
                    }

                    // 2. Resources Check
                    if (planet.resources) {
                        newResources += planet.resources;
                    }

                    // 3. Influence Check
                    if (planet.influence) {
                        newInfluence += planet.influence;
                    }

                    // 4. Space Station Check
                    if (planet.spaceStation) {
                        newSpaceStations += 1;
                    }
                }
            }
        }

        // Update the component state ONCE with all new values
        this.setState({
            legendaries: newLegendaryPlanets,
            resources: newResources,
            influence: newInfluence,
            spaceStations: newSpaceStations
        }, () => {
            console.log(`MapInfo: Finished single-pass processing.`);
            console.log(`Legendaries: ${this.state.legendaries.length}, Resources: ${this.state.resources}, Influence: ${this.state.influence}, Space Stations: ${this.state.spaceStations}`);
        });
    }

    render() {
        // Remember to add your rendering logic here based on the state!
        // For example, display the calculated values:
        return (
            <div className="col-12 col-md-4 text-start">
                {/* Inner card with styles. Added text-dark for high contrast. */}
                <div className="p-4 border border-secondary rounded-lg shadow-lg bg-light mt-4 text-dark">
                    <h3 className="mb-3 text-secondary border-bottom pb-2">Map Statistics</h3>
                    <p className="mb-1"><strong>Legendary Planets Found:</strong> {this.state.legendaries.length}</p>
                    <p className="mb-1"><strong>Total Resources:</strong> {this.state.resources}</p>
                    <p className="mb-1"><strong>Total Influence:</strong> {this.state.influence}</p>
                    <p className="mb-0"><strong>Space Stations:</strong> {this.state.spaceStations}</p>
                </div>
            </div>
        );
    };
};

export default MapInfo;